=== octokit/webhooks/payload-schemas/api.github.com/deployment_review/requested.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "deployment_review$requested",
  "type": "object",
  "required": [
    "action",
    "environment",
    "workflow_run",
    "since",
    "workflow_job_run",
    "reviewers",
    "requestor",
    "repository",
    "organization",
    "sender"
  ],
  "properties": {
    "action": { "type": "string", "enum": ["requested"] },
    "workflow_run": {
      "oneOf": [
        { "$ref": "common/workflow-run.schema.json" },
        { "type": "null" }
      ]
    },
    "since": { "type": "string", "format": "date-time" },
    "workflow_job_run": {
      "type": "object",
      "required": [
        "id",
        "name",
        "status",
        "conclusion",
        "html_url",
        "created_at",
        "updated_at",
        "environment"
      ],
      "properties": {
        "id": { "type": "integer" },
        "name": { "type": "string" },
        "status": {
          "type": "string",
          "enum": ["queued", "in_progress", "completed", "waiting"]
        },
        "conclusion": {
          "type": ["string", "null"],
          "enum": ["success", "failure", "cancelled", "skipped", null]
        },
        "html_url": { "type": "string", "format": "uri" },
        "created_at": { "type": "string", "format": "date-time" },
        "updated_at": { "type": "string", "format": "date-time" },
        "environment": { "type": "string" }
      },
      "additionalProperties": false
    },
    "environment": { "type": "string" },
    "reviewers": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "required": ["type", "reviewer"],
            "properties": {
              "type": { "type": "string", "enum": ["User"] },
              "reviewer": { "$ref": "common/user.schema.json" }
            },
            "additionalProperties": false
          },
          {
            "type": "object",
            "required": ["type", "reviewer"],
            "properties": {
              "type": { "type": "string", "enum": ["Team"] },
              "reviewer": { "$ref": "common/team.schema.json" }
            },
            "additionalProperties": false
          }
        ]
      }
    },
    "requestor": { "$ref": "common/user.schema.json" },
    "repository": { "$ref": "common/repository.schema.json" },
    "organization": { "$ref": "common/organization.schema.json" },
    "sender": { "$ref": "common/user.schema.json" },
    "installation": { "$ref": "common/installation-lite.schema.json" }
  },
  "additionalProperties": false,
  "title": "deployment_review requested event"
}

=== octokit/webhooks/payload-examples/api.github.com/deployment_review/requested.payload.json
{
  "action": "requested",
  "workflow_run": {
    "id": 5453085689,
    "name": "Build pull_request 3 by @ilmax",
    "node_id": "WFR_kwLOJMUtSc8AAAABRQd7-Q",
    "head_branch": "sample",
    "head_sha": "5275a45b7e99c7fd7265b790392c10a74101a67a",
    "path": ".github/workflows/pr.yaml",
    "display_title": "Build pull_request 3 by @ilmax",
    "run_number": 15,
    "event": "pull_request",
    "status": "waiting",
    "conclusion": null,
    "workflow_id": 51845905,
    "check_suite_id": 14047292119,
    "check_suite_node_id": "CS_kwDOJMUtSc8AAAADRUiq1w",
    "url": "https://api.github.com/repos/terraform-test-github/sample-app/actions/runs/5453085689",
    "html_url": "https://github.com/terraform-test-github/sample-app/actions/runs/5453085689",
    "pull_requests": [
      {
        "url": "https://api.github.com/repos/terraform-test-github/sample-app/pulls/3",
        "id": 1419286779,
        "number": 3,
        "head": {
          "ref": "sample",
          "sha": "5275a45b7e99c7fd7265b790392c10a74101a67a",
          "repo": {
            "id": 616901961,
            "url": "https://api.github.com/repos/terraform-test-github/sample-app",
            "name": "sample-app"
          }
        },
        "base": {
          "ref": "main",
          "sha": "ab687588c4b0db742f5145fe8fb3005dfce9ebe1",
          "repo": {
            "id": 616901961,
            "url": "https://api.github.com/repos/terraform-test-github/sample-app",
            "name": "sample-app"
          }
        }
      }
    ],
    "created_at": "2023-07-04T09:28:10Z",
    "updated_at": "2023-07-04T09:28:15Z",
    "actor": {
      "login": "ilmax",
      "id": 3263338,
      "node_id": "MDQ6VXNlcjMyNjMzMzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3263338?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ilmax",
      "html_url": "https://github.com/ilmax",
      "followers_url": "https://api.github.com/users/ilmax/followers",
      "following_url": "https://api.github.com/users/ilmax/following{/other_user}",
      "gists_url": "https://api.github.com/users/ilmax/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ilmax/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ilmax/subscriptions",
      "organizations_url": "https://api.github.com/users/ilmax/orgs",
      "repos_url": "https://api.github.com/users/ilmax/repos",
      "events_url": "https://api.github.com/users/ilmax/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ilmax/received_events",
      "type": "User",
      "site_admin": false
    },
    "run_attempt": 1,
    "referenced_workflows": [],
    "run_started_at": "2023-07-04T09:28:10Z",
    "triggering_actor": {
      "login": "ilmax",
      "id": 3263338,
      "node_id": "MDQ6VXNlcjMyNjMzMzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3263338?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ilmax",
      "html_url": "https://github.com/ilmax",
      "followers_url": "https://api.github.com/users/ilmax/followers",
      "following_url": "https://api.github.com/users/ilmax/following{/other_user}",
      "gists_url": "https://api.github.com/users/ilmax/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ilmax/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ilmax/subscriptions",
      "organizations_url": "https://api.github.com/users/ilmax/orgs",
      "repos_url": "https://api.github.com/users/ilmax/repos",
      "events_url": "https://api.github.com/users/ilmax/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ilmax/received_events",
      "type": "User",
      "site_admin": false
    },
    "jobs_url": "https://api.github.com/repos/terraform-test-github/sample-app/actions/runs/5453085689/jobs",
    "logs_url": "https://api.github.com/repos/terraform-test-github/sample-app/actions/runs/5453085689/logs",
    "check_suite_url": "https://api.github.com/repos/terraform-test-github/sample-app/check-suites/14047292119",
    "artifacts_url": "https://api.github.com/repos/terraform-test-github/sample-app/actions/runs/5453085689/artifacts",
    "cancel_url": "https://api.github.com/repos/terraform-test-github/sample-app/actions/runs/5453085689/cancel",
    "rerun_url": "https://api.github.com/repos/terraform-test-github/sample-app/actions/runs/5453085689/rerun",
    "previous_attempt_url": null,
    "workflow_url": "https://api.github.com/repos/terraform-test-github/sample-app/actions/workflows/51845905",
    "head_commit": {
      "id": "5275a45b7e99c7fd7265b790392c10a74101a67a",
      "tree_id": "ab9c9b5d743236041bc83243b4db56b0dc5f14fa",
      "message": "Trigger",
      "timestamp": "2023-07-04T09:28:05Z",
      "author": {
        "name": "Massimiliano Donini",
        "email": "massimiliano.donini@gmail.com"
      },
      "committer": { "name": "GitHub", "email": "noreply@github.com" }
    },
    "repository": {
      "id": 616901961,
      "node_id": "R_kgDOJMUtSQ",
      "name": "sample-app",
      "full_name": "terraform-test-github/sample-app",
      "private": false,
      "owner": {
        "login": "terraform-test-github",
        "id": 123865115,
        "node_id": "O_kgDOB2IIGw",
        "avatar_url": "https://avatars.githubusercontent.com/u/123865115?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/terraform-test-github",
        "html_url": "https://github.com/terraform-test-github",
        "followers_url": "https://api.github.com/users/terraform-test-github/followers",
        "following_url": "https://api.github.com/users/terraform-test-github/following{/other_user}",
        "gists_url": "https://api.github.com/users/terraform-test-github/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/terraform-test-github/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/terraform-test-github/subscriptions",
        "organizations_url": "https://api.github.com/users/terraform-test-github/orgs",
        "repos_url": "https://api.github.com/users/terraform-test-github/repos",
        "events_url": "https://api.github.com/users/terraform-test-github/events{/privacy}",
        "received_events_url": "https://api.github.com/users/terraform-test-github/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/terraform-test-github/sample-app",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/terraform-test-github/sample-app",
      "forks_url": "https://api.github.com/repos/terraform-test-github/sample-app/forks",
      "keys_url": "https://api.github.com/repos/terraform-test-github/sample-app/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/terraform-test-github/sample-app/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/terraform-test-github/sample-app/teams",
      "hooks_url": "https://api.github.com/repos/terraform-test-github/sample-app/hooks",
      "issue_events_url": "https://api.github.com/repos/terraform-test-github/sample-app/issues/events{/number}",
      "events_url": "https://api.github.com/repos/terraform-test-github/sample-app/events",
      "assignees_url": "https://api.github.com/repos/terraform-test-github/sample-app/assignees{/user}",
      "branches_url": "https://api.github.com/repos/terraform-test-github/sample-app/branches{/branch}",
      "tags_url": "https://api.github.com/repos/terraform-test-github/sample-app/tags",
      "blobs_url": "https://api.github.com/repos/terraform-test-github/sample-app/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/terraform-test-github/sample-app/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/terraform-test-github/sample-app/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/terraform-test-github/sample-app/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/terraform-test-github/sample-app/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/terraform-test-github/sample-app/languages",
      "stargazers_url": "https://api.github.com/repos/terraform-test-github/sample-app/stargazers",
      "contributors_url": "https://api.github.com/repos/terraform-test-github/sample-app/contributors",
      "subscribers_url": "https://api.github.com/repos/terraform-test-github/sample-app/subscribers",
      "subscription_url": "https://api.github.com/repos/terraform-test-github/sample-app/subscription",
      "commits_url": "https://api.github.com/repos/terraform-test-github/sample-app/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/terraform-test-github/sample-app/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/terraform-test-github/sample-app/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/terraform-test-github/sample-app/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/terraform-test-github/sample-app/contents/{+path}",
      "compare_url": "https://api.github.com/repos/terraform-test-github/sample-app/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/terraform-test-github/sample-app/merges",
      "archive_url": "https://api.github.com/repos/terraform-test-github/sample-app/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/terraform-test-github/sample-app/downloads",
      "issues_url": "https://api.github.com/repos/terraform-test-github/sample-app/issues{/number}",
      "pulls_url": "https://api.github.com/repos/terraform-test-github/sample-app/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/terraform-test-github/sample-app/milestones{/number}",
