=== octokit/webhooks/payload-schemas/schemas/integration_installation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "integration_installation",

  "type": "object",
  "required": ["action", "installation", "repositories", "sender"],
  "properties": {
    "action": {
      "type": "string",
      "enum": ["created"]
    },
    "installation": {
      "$ref": "$installation"
    },
    "repositories": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "anyOf": [
          {
            "type": "object",
            "required": ["id", "node_id", "name", "full_name", "private"],
            "properties": {
              "id": {
                "type": "integer"
              },
              "node_id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "full_name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              }
            },
            "additionalProperties": false
          }
        ]
      }
    },
    "sender": {
      "$ref": "$sender"
    }
  },
  "additionalProperties": false
}

=== octokit/webhooks/payload-examples/api.github.com/installation.created.payload.json
{
  "action": "created",
  "installation": {
    "id": 957387,
    "account": {
      "login": "Codertocat",
      "id": 21031067,
      "node_id": "MDQ6VXNlcjIxMDMxMDY3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Codertocat",
      "html_url": "https://github.com/Codertocat",
      "followers_url": "https://api.github.com/users/Codertocat/followers",
      "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
      "organizations_url": "https://api.github.com/users/Codertocat/orgs",
      "repos_url": "https://api.github.com/users/Codertocat/repos",
      "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Codertocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "repository_selection": "selected",
    "access_tokens_url": "https://api.github.com/app/installations/957387/access_tokens",
    "repositories_url": "https://api.github.com/installation/repositories",
    "html_url": "https://github.com/settings/installations/957387",
    "app_id": 29310,
    "target_id": 21031067,
    "target_type": "User",
    "permissions": {
      "administration": "write",
      "checks": "write",
      "contents": "write",
      "deployments": "write",
      "issues": "write",
      "pages": "write",
      "pull_requests": "write",
      "repository_hooks": "write",
      "repository_projects": "write",
      "statuses": "write",
      "metadata": "read",
      "vulnerability_alerts": "read"
    },
    "events": [

    ],
    "created_at": 1557933591,
    "updated_at": 1557933591,
    "single_file_name": null
  },
  "repositories": [
    {
      "id": 186853002,
      "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
      "name": "Hello-World",
      "full_name": "Codertocat/Hello-World",
      "private": false
    }
  ],
  "sender": {
    "login": "Codertocat",
    "id": 21031067,
    "node_id": "MDQ6VXNlcjIxMDMxMDY3",
    "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Codertocat",
    "html_url": "https://github.com/Codertocat",
    "followers_url": "https://api.github.com/users/Codertocat/followers",
    "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
    "organizations_url": "https://api.github.com/users/Codertocat/orgs",
    "repos_url": "https://api.github.com/users/Codertocat/repos",
    "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Codertocat/received_events",
    "type": "User",
    "site_admin": false
  }
}
