=== octokit/webhooks/payload-schemas/schemas/sponsorship.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "sponsorship",

  "type": "object",
  "required": ["action", "sponsorship", "sender"],
  "properties": {
    "action": {
      "type": "string",
      "enum": [
        "created",
        "cancelled",
        "edited",
        "tier_changed",
        "pending_cancellation",
        "pending_tier_change"
      ]
    },
    "sponsorship": {
      "type": "object",
      "required": [
        "node_id",
        "created_at",
        "sponsorable",
        "sponsor",
        "privacy_level",
        "tier"
      ],
      "properties": {
        "node_id": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "sponsorable": {
          "type": "object",
          "required": [
            "login",
            "id",
            "node_id",
            "avatar_url",
            "gravatar_id",
            "url",
            "html_url",
            "followers_url",
            "following_url",
            "gists_url",
            "starred_url",
            "subscriptions_url",
            "organizations_url",
            "repos_url",
            "events_url",
            "received_events_url",
            "type",
            "site_admin"
          ],
          "properties": {
            "login": {
              "type": "string"
            },
            "id": {
              "type": "integer"
            },
            "node_id": {
              "type": "string"
            },
            "avatar_url": {
              "type": "string"
            },
            "gravatar_id": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "html_url": {
              "type": "string"
            },
            "followers_url": {
              "type": "string"
            },
            "following_url": {
              "type": "string"
            },
            "gists_url": {
              "type": "string"
            },
            "starred_url": {
              "type": "string"
            },
            "subscriptions_url": {
              "type": "string"
            },
            "organizations_url": {
              "type": "string"
            },
            "repos_url": {
              "type": "string"
            },
            "events_url": {
              "type": "string"
            },
            "received_events_url": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "site_admin": {
              "type": "boolean"
            }
          },
          "additionalProperties": false
        },
        "sponsor": {
          "type": "object",
          "required": [
            "login",
            "id",
            "node_id",
            "avatar_url",
            "gravatar_id",
            "url",
            "html_url",
            "followers_url",
            "following_url",
            "gists_url",
            "starred_url",
            "subscriptions_url",
            "organizations_url",
            "repos_url",
            "events_url",
            "received_events_url",
            "type",
            "site_admin"
          ],
          "properties": {
            "login": {
              "type": "string"
            },
            "id": {
              "type": "integer"
            },
            "node_id": {
              "type": "string"
            },
            "avatar_url": {
              "type": "string"
            },
            "gravatar_id": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "html_url": {
              "type": "string"
            },
            "followers_url": {
              "type": "string"
            },
            "following_url": {
              "type": "string"
            },
            "gists_url": {
              "type": "string"
            },
            "starred_url": {
              "type": "string"
            },
            "subscriptions_url": {
              "type": "string"
            },
            "organizations_url": {
              "type": "string"
            },
            "repos_url": {
              "type": "string"
            },
            "events_url": {
              "type": "string"
            },
            "received_events_url": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "site_admin": {
              "type": "boolean"
            }
          },
          "additionalProperties": false
        },
        "privacy_level": {
          "type": "string"
        },
        "tier": {
          "type": "object",
          "required": [
            "node_id",
            "created_at",
            "description",
            "monthly_price_in_cents",
            "monthly_price_in_dollars",
            "name"
          ],
          "properties": {
            "node_id": {
              "type": "string"
            },
            "created_at": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "monthly_price_in_cents": {
              "type": "integer"
            },
            "monthly_price_in_dollars": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "effective_date": {
      "type": "string"
    },
    "changes": {
      "type": "object",
      "required": ["tier"],
      "properties": {
        "tier": {
          "type": "object",
          "required": ["from"],
          "properties": {
            "from": {
              "type": "object",
              "required": [
                "node_id",
                "created_at",
                "description",
                "monthly_price_in_cents",
                "monthly_price_in_dollars",
                "name"
              ],
              "properties": {
                "node_id": {
                  "type": "string"
                },
                "created_at": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "monthly_price_in_cents": {
                  "type": "integer"
                },
                "monthly_price_in_dollars": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "sender": {
      "$ref": "common/user.schema.json"
    }
  },
  "additionalProperties": false
}

=== octokit/webhooks/payload-examples/api.github.com/sponsorship.downgraded.payload.json
{
    "action": "pending_tier_change",
    "sponsorship": {
        "node_id": "MDExOlNwb25zb3JzaGlwMQ==",
        "created_at": "2019-12-20T19:24:46+00:00",
        "sponsorable": {
            "login": "octocat",
            "id": 5,
            "node_id": "MDQ6VXNlcjU=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/5?",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "sponsor": {
            "login": "monalisa",
            "id": 2,
            "node_id": "MDQ6VXNlcjI=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/2?",
            "gravatar_id": "",
            "url": "https://api.github.com/users/monalisa",
            "html_url": "https://github.com/monalisa",
            "followers_url": "https://api.github.com/users/monalisa/followers",
            "following_url": "https://api.github.com/users/monalisa/following{/other_user}",
            "gists_url": "https://api.github.com/users/monalisa/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/monalisa/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/monalisa/subscriptions",
            "organizations_url": "https://api.github.com/users/monalisa/orgs",
            "repos_url": "https://api.github.com/users/monalisa/repos",
            "events_url": "https://api.github.com/users/monalisa/events{/privacy}",
            "received_events_url": "https://api.github.com/users/monalisa/received_events",
            "type": "User",
            "site_admin": true
        },
        "privacy_level": "private",
        "tier": {
            "node_id": "MDEyOlNwb25zb3JzVGllcjE=",
            "created_at": "2019-12-20T19:17:05Z",
            "description": "foo",
            "monthly_price_in_cents": 500,
            "monthly_price_in_dollars": 5,
            "name": "$5 a month"
        }
    },
    "changes": {
        "tier": {
            "from": {
                "node_id": "MDEyOlNwb25zb3JzVGllcjI=",
                "created_at": "2019-12-20T19:26:26Z",
                "description": "bar",
                "monthly_price_in_cents": 1000,
                "monthly_price_in_dollars": 10,
                "name": "$10 a month"
            }
        }
    },
    "effective_date": "2019-12-30T00:00:00+00:00",
    "sender": {
        "login": "monalisa",
        "id": 2,
        "node_id": "MDQ6VXNlcjI=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/2?",
        "gravatar_id": "",
        "url": "https://api.github.com/users/monalisa",
        "html_url": "https://github.com/monalisa",
        "followers_url": "https://api.github.com/users/monalisa/followers",
        "following_url": "https://api.github.com/users/monalisa/following{/other_user}",
        "gists_url": "https://api.github.com/users/monalisa/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/monalisa/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/monalisa/subscriptions",
        "organizations_url": "https://api.github.com/users/monalisa/orgs",
        "repos_url": "https://api.github.com/users/monalisa/repos",
        "events_url": "https://api.github.com/users/monalisa/events{/privacy}",
        "received_events_url": "https://api.github.com/users/monalisa/received_events",
        "type": "User",
        "site_admin": true
    }
}
