=== octokit/webhooks/payload-schemas/api.github.com/code_scanning_alert/fixed.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "code_scanning_alert$fixed",
  "type": "object",
  "required": ["action", "alert", "ref", "commit_oid", "repository", "sender"],
  "properties": {
    "action": { "type": "string", "enum": ["fixed"] },
    "alert": {
      "type": "object",
      "description": "The code scanning alert involved in the event.",
      "required": [
        "number",
        "created_at",
        "url",
        "html_url",
        "instances",
        "state",
        "dismissed_by",
        "dismissed_at",
        "dismissed_reason",
        "rule",
        "tool"
      ],
      "properties": {
        "number": {
          "type": "integer",
          "description": "The code scanning alert number."
        },
        "created_at": {
          "type": "string",
          "format": "date-time",
          "description": "The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ.`"
        },
        "url": { "type": "string", "format": "uri" },
        "html_url": {
          "type": "string",
          "format": "uri",
          "description": "The GitHub URL of the alert resource."
        },
        "instances": {
          "type": "array",
          "items": {
            "allOf": [
              { "$ref": "common/alert-instance.schema.json" },
              {
                "type": "object",
                "required": ["state"],
                "properties": {
                  "state": { "type": "string", "enum": ["fixed"] }
                },
                "tsAdditionalProperties": false
              }
            ]
          }
        },
        "state": {
          "type": "string",
          "description": "State of a code scanning alert.",
          "enum": ["fixed"]
        },
        "dismissed_by": {
          "oneOf": [{ "$ref": "common/user.schema.json" }, { "type": "null" }]
        },
        "dismissed_at": {
          "type": ["string", "null"],
          "format": "date-time",
          "description": "The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."
        },
        "dismissed_reason": {
          "type": ["string", "null"],
          "enum": ["false positive", "won't fix", "used in tests", null],
          "description": "The reason for dismissing or closing the alert. Can be one of: `false positive`, `won't fix`, and `used in tests`."
        },
        "rule": {
          "type": "object",
          "required": ["id", "severity", "description"],
          "properties": {
            "id": {
              "type": "string",
              "description": "A unique identifier for the rule used to detect the alert."
            },
            "severity": {
              "type": ["string", "null"],
              "enum": ["none", "note", "warning", "error", null],
              "description": "The severity of the alert."
            },
            "description": {
              "type": "string",
              "description": "A short description of the rule used to detect the alert."
            },
            "name": { "type": "string" },
            "full_description": { "type": "string" },
            "tags": { "type": "null" },
            "help": { "type": "null" }
          },
          "additionalProperties": false
        },
        "tool": {
          "type": "object",
          "required": ["name", "version"],
          "properties": {
            "name": {
              "type": "string",
              "description": "The name of the tool used to generate the code scanning analysis alert."
            },
            "version": {
              "type": ["string", "null"],
              "description": "The version of the tool used to detect the alert."
            },
            "guid": { "type": ["string", "null"] }
          },
          "additionalProperties": false
        },
        "most_recent_instance": { "$ref": "common/alert-instance.schema.json" },
        "instances_url": { "type": "string", "format": "uri" }
      },
      "additionalProperties": false
    },
    "ref": {
      "type": "string",
      "description": "The Git reference of the code scanning alert. When the action is `reopened_by_user` or `closed_by_user`, the event was triggered by the `sender` and this value will be empty."
    },
    "commit_oid": {
      "type": "string",
      "description": "The commit SHA of the code scanning alert. When the action is `reopened_by_user` or `closed_by_user`, the event was triggered by the `sender` and this value will be empty."
    },
    "repository": { "$ref": "common/repository.schema.json" },
    "sender": { "$ref": "common/github-org.schema.json" },
    "installation": { "$ref": "common/installation-lite.schema.json" },
    "organization": { "$ref": "common/organization.schema.json" }
  },
  "additionalProperties": false,
  "title": "code_scanning_alert fixed event"
}

=== octokit/webhooks/payload-examples/api.github.com/code_scanning_alert/fixed.payload.json
{
  "action": "fixed",
  "alert": {
    "number": 10,
    "created_at": "2021-02-11T03:10:43Z",
    "url": "https://api.github.com/repos/Codertocat/Hello-World/code-scanning/alerts/10",
    "html_url": "https://github.com/Codertocat/Hello-World/security/code-scanning/10",
    "state": "fixed",
    "dismissed_by": null,
    "dismissed_at": null,
    "dismissed_reason": null,
    "rule": {
      "id": "java/sql-injection",
      "severity": "error",
      "description": "Query built from user-controlled sources",
      "name": "",
      "full_description": "Building a SQL or Java Persistence query from user-controlled sources is vulnerable to insertion of malicious code by the user.",
      "tags": null,
      "help": null
    },
    "tool": { "name": "CodeQL", "guid": null, "version": null },
    "most_recent_instance": {
      "ref": "refs/pull/11/merge",
      "analysis_key": ".github/workflows/code-scanning.yml:build",
      "environment": "{}",
      "state": "fixed",
      "commit_sha": "0048a27ccd962b83b1bd781bbc6f7e8fd1b2caea",
      "message": { "text": "" },
      "location": {
        "path": "src/main/java/com/github/demo/service/BookService.java",
        "start_line": 84,
        "end_line": 84,
        "start_column": 51,
        "end_column": 56
      },
      "classifications": []
    },
    "instances_url": "https://api.github.com/repos/Codertocat/Hello-World/code-scanning/alerts/10/instances",
    "instances": [
      {
        "ref": "refs/pull/11/merge",
        "analysis_key": ".github/workflows/code-scanning.yml:build",
        "environment": "{}",
        "state": "fixed",
        "commit_sha": "0048a27ccd962b83b1bd781bbc6f7e8fd1b2caea",
        "message": { "text": "" },
        "location": {
          "path": "src/main/java/com/github/demo/service/BookService.java",
          "start_line": 84,
          "end_line": 84,
          "start_column": 51,
          "end_column": 56
        },
        "classifications": []
      }
    ]
  },
  "ref": "refs/pull/11/merge",
  "commit_oid": "c5bf87afac650dbcb5fd97cfc22fcae5303da8e1",
  "repository": {
    "id": 337911632,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMzc5MTE2MzI=",
    "name": "Hello-World",
    "full_name": "Codertocat/Hello-World",
    "private": true,
    "owner": {
      "login": "Codertocat",
      "id": 21031067,
      "node_id": "MDQ6VXNlcjIxMDMxMDY3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Codertocat",
      "html_url": "https://github.com/Codertocat",
      "followers_url": "https://api.github.com/users/Codertocat/followers",
      "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
      "organizations_url": "https://api.github.com/users/Codertocat/orgs",
      "repos_url": "https://api.github.com/users/Codertocat/repos",
      "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Codertocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Codertocat/Hello-World",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Codertocat/Hello-World",
    "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
    "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
    "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
    "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
    "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
    "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
    "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
    "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
    "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
    "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
    "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
    "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
    "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
    "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
    "created_at": "2021-02-11T02:36:00Z",
    "updated_at": "2021-02-11T02:46:41Z",
    "pushed_at": "2021-02-13T04:19:08Z",
    "git_url": "git://github.com/Codertocat/Hello-World.git",
    "ssh_url": "org-38940897@github.com:Codertocat/Hello-World.git",
    "clone_url": "https://github.com/Codertocat/Hello-World.git",
    "svn_url": "https://github.com/Codertocat/Hello-World",
    "homepage": "",
    "size": 533,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": false,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 11,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "forks": 0,
    "open_issues": 11,
    "watchers": 0,
    "default_branch": "master"
  },
  "organization": {
    "login": "Octocoders",
    "id": 6,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjY=",
    "url": "https://api.github.com/orgs/Octocoders",
    "repos_url": "https://api.github.com/orgs/Octocoders/repos",
    "events_url": "https://api.github.com/orgs/Octocoders/events",
    "hooks_url": "https://api.github.com/orgs/Octocoders/hooks",
    "issues_url": "https://api.github.com/orgs/Octocoders/issues",
    "members_url": "https://api.github.com/orgs/Octocoders/members{/member}",
    "public_members_url": "https://api.github.com/orgs/Octocoders/public_members{/member}",
    "avatar_url": "https://avatars0.githubusercontent.com/u/6?",
    "description": ""
  },
  "sender": {
    "login": "github",
    "id": 9919,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/github",
    "html_url": "https://github.com/github",
    "followers_url": "https://api.github.com/users/github/followers",
    "following_url": "https://api.github.com/users/github/following{/other_user}",
    "gists_url": "https://api.github.com/users/github/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/github/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/github/subscriptions",
    "organizations_url": "https://api.github.com/users/github/orgs",
    "repos_url": "https://api.github.com/users/github/repos",
    "events_url": "https://api.github.com/users/github/events{/privacy}",
    "received_events_url": "https://api.github.com/users/github/received_events",
    "type": "Organization",
    "site_admin": false
  },
  "installation": {
    "id": 14662836,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTQ2NjI4MzY="
  }
}
